### ISSUE TITLE
Missing python-serial package for micon_boot.service

### ISSUE THREAD

**Issue by dargow** [1000001101000/Debian_on_Intel_Terastations#12]
I installed image [ts-bookworm-installer.iso](https://github.com/1000001101000/Debian_on_Intel_Terastations/blob/master/installer-image/Bookworm/ts-bookworm-installer.iso) from [installer-image](https://github.com/1000001101000/Debian_on_Intel_Terastations/tree/master/installer-image)
And noticed error in service micon_boot.service log:
```
12:26 AM
Failed to start micon_boot.service - Tell Terastation it finished booting so it doesnt shutdown.
systemd
12:26 AM
micon_boot.service: Failed with result 'exit-code'.
systemd
12:26 AM
micon_boot.service: Main process exited, code=exited, status=1/FAILURE
systemd
12:26 AM
ModuleNotFoundError: No module named 'serial'
micon_startup.py
12:26 AM
import serial
micon_startup.py
12:26 AM
File "/usr/local/bin/micon_scripts/libmicon.py", line 6, in <module>
micon_startup.py
12:26 AM
import libmicon
micon_startup.py
12:26 AM
File "/usr/local/bin/micon_scripts/micon_startup.py", line 3, in <module>
micon_startup.py
12:26 AM
Traceback (most recent call last):
micon_startup.py
12:26 AM
Starting micon_boot.service - Tell Terastation it finished booting so it doesnt shutdown...
```

I googled this error and just run:
```
sudo apt install python3-serial
```
After this service working.
Please provide this in the installation script for builds

**Comment by 1000001101000** [comment]
It’s one of the packages added in the preseed config:
https://github.com/1000001101000/Debian_on_Intel_Terastations/blob/eba9a178bc072e7297d8485779de35bde225e218/installer-image/Bookworm/build/preseed.cfg#L58

I would expect the install to error out if it was unable to install it for some reason.

can you check if those other packages appear to be installed?

**Comment by 1000001101000** [comment]
I ran a quick install in qemu, the python3-serial package installed and the micon scripts behaved normally.

I assume whatever happened was specific to your install… though I have no idea what that could have been.

**Comment by dargow** [comment]
Strange.
It's a pity I don't have installation logs left.
The remaining packages seem to be installed.
True, I'm still confused by messages in syslog
```
3:44 PM
Failed to find module 'pinctrl-dnv'
systemd-modules-load
3:44 PM
Failed to find module 'gpio-ich'
systemd-modules-load
3:44 PM
Failed to find module 'gpio-it87'
systemd-modules-load
3:44 PM
Failed to find module 'it87ts'
systemd-modules-load
```
But it doesn't seem like they have any effect on the ability of specific controllers to work.

I think the topic can be closed if it is not possible to repeat similar problems.
I hope if anyone has a similar problem, they will find this issue.
